name: Backend PR Check

on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-pr-check.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: deeptalk_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: |
        cd backend
        mvn clean verify
    
    - name: Test Application Startup
      run: |
        cd backend
        mvn spring-boot:run &
        # 等待应用启动
        sleep 30
        # 检查应用是否正常响应
        curl -f http://localhost:8080/actuator/health || exit 1
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/deeptalk_test
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
        SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
        SPRING_JPA_SHOW_SQL: true 